.TH "gather_profile_stats.py" "1" "August 2007" "Django Project" ""
.SH "NAME"
gather_profile_stats.py \- Django ウェブフレームワークのためのパフォー
マンス解析ツール
.SH "SYNOPSIS"
.B python gather_profile_stats.py
.I <path>

.SH "DESCRIPTION"
このユーティリティスクリプトは、 Python の hotshot プロファイラを使っ
て生成されたプロファイルログを収集します。唯一の引数として、プロファイ
ルログの入ったディレクトリへの絶対パスをとります。

.SH "SEE ALSO"
Django プロジェクトの wiki にある、 Django アプリケーションのプロファ
イリングに関する議論:
.sp
.I http://www.djangoproject.com/wiki/ProfilingDjango

.SH "AUTHORS/CREDITS"
このプログラムの最初のバージョンは、米国カンザス州ローレンスの World
Online 社で開発されました。プログラムに寄与した開発者たちのリストは
Django 配布物中の AUTHORS ファイルを参照してください。

.SH "LICENSE"
新 BSD ライセンス (New BSD license) です。完全な形式のライセンステキストは、 Django 配布物中の LICENSE ファイルを参照してください。

